server:
  port: 10010 # 网关端口
spring:
  application:
    name: gatewayservice # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: userservice # 路由id，自定义，只需要唯一即可
          uri: lb://userservice # 路由的目标地址，lb表示负载均衡，后面跟服务名称
          # uri: http://localhost:8081 # 路由的目标地址，http就是固定地址
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**,/common/** # 这个是按照路径匹配，只要是以/user或/common开头的，就符合规则
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: stockservice
          uri: lb://stockservice
          predicates:
            - Path=/stock/**
        - id: purchaseservice
          uri: lb://purchaseservice
          predicates:
            - Path=/purchase/**
        - id: goodsservice
          uri: lb://goodsservice
          predicates:
            - Path=/good/**,/common/**
        - id: defrayservice
          uri: lb://defrayservice
          predicates:
            - Path=/defray/**